## BOX_1_SIEM
services:
# GRAFANA
  grafana:
    image: grafana/grafana:latest  # Utilise l'image officielle Grafana
    container_name: grafana  # Donne un nom au conteneur
    ports:
      - "3000:3000"  # Mappe le port local 3000 au port 3000 de Grafana dans le conteneur
    volumes:
      - ./data/grafana-data:/var/lib/grafana  # Monte un volume pour persister les données de Grafana
    depends_on:
      - loki  # Spécifie que Grafana dépend de Loki
    networks:
      - net_siem_vuln
# LOKI
  loki:
    image: grafana/loki:latest  
    container_name: loki  
    ports:
      - "3100:3100"  
    volumes:
      - ./data/loki-data:/var/lib/loki  
    networks:
      - net_siem_vuln
# PROMTAIL
  promtail:
    image: grafana/promtail:latest  # Utilise l'image officielle Promtail
    container_name: promtail  # Nom du conteneur
    volumes:
      - ./config/promtail-config/promtail-config.yml:/etc/promtail/config.yml  # Fichier de configuration personnalisé pour Promtail
      - ./data/suricata-logs:/var/log/suricata   # Accès aux logs de Suricata
    command: -config.file=/etc/promtail/config.yml  # Spécifie le fichier de configuration
    depends_on:
      - loki  # Promtail dépend de Loki
    networks:
      - net_siem_vuln
# SURICATA
  suricata:
    image: jasonish/suricata:6.0.4-arm64v8  # Image adaptée pour ARM
    container_name: suricata
    privileged: true  # Nécessaire pour l'accès réseau
    networks:
      - net_siem_vuln
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
        - SURICATA_OPTIONS=-i eth0 
    volumes:
      - ./config/suricata-config:/etc/suricata  # Montre le fichier de configuration
      - ./data/suricata-logs:/var/log/suricata  # Permet de persister les logs
      - ./data/suricata-rules/suricata.rules:/var/lib/suricata/rules/suricata.rules  # Ajoute un volume pour les règles personnalisées

networks:
  net_siem_vuln:
    external: true
