## BOX_2_OUTILS_OFFENSIFS
services:
# CAIDO
  caido:
    image: caido/caido:latest
    container_name: caido
    ports:
    - "8080:8080"
    volumes:
      - ./data:/home/caido/.local/share/caido
    platform: linux/amd64
    networks:
      - net_attack_vuln
# NMAP
  nmap:
    build:
      context: ./Dockerfiles/nmap
    container_name: nmap
    networks:
      - net_attack_vuln
# SQLMAP
  sqlmap:
    build:
      context: ./Dockerfiles/sqlmap/.
    volumes:
      - ./Dockerfiles/sqlmap/data/queries:/queries
      - ./Dockerfiles/sqlmap/data/out:/root/.local/share/sqlmap/output
    networks:
      - net_attack_vuln

networks:
  net_attack_vuln:
    external: true